spring:
    data:
      cassandra:
        port: 9042
        contact-points: mycassandra
        local-datacenter: datacenter1
        keyspace-name: mykeyspace
        entity-base-package: com.example.movieapplication.model
